import type { Metadata } from 'next';
import { Geist, Geist_Mono, Zen_Dots } from 'next/font/google';
import AuthProvider from './auth/Provider';

import './globals.css';
import NavBar from './NavBar';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const nunitoSans = Zen_Dots({
  variable: '--font-zen-dots',
  subsets: ['latin'],
  weight: ['400'],
});

// For SEO
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  openGraph: {
    images: [
      {
        url: 'https://www.rewwind.co/images/collections_image.png',
        width: 1200,
        height: 630,
        alt: 'Rewwind Collections',
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' data-theme='dark'>
      <body
        className={`${nunitoSans.variable} ${geistSans.variable} ${geistMono.variable} antialiased h-full`}
      >
        <AuthProvider>
          <NavBar />
          {/* <main className='p-6 relative h-[calc(100vh-64px)] '>{children}</main> */}
          <main className='p-6'>{children}</main>
        </AuthProvider>
      </body>
    </html>
  );
}
